"""add pushlog

Revision ID: 116bbb73bbdb
Revises: 888a5f5bad86
Create Date: 2026-02-27 02:40:24.013487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '116bbb73bbdb'
down_revision = '888a5f5bad86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('receiver_bipupu_id', sa.String(length=50), nullable=False),
    sa.Column('content_preview', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'SKIPPED', name='push_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_push_receiver_created', 'push_logs', ['receiver_bipupu_id', 'created_at'], unique=False)
    op.create_index('idx_push_service_created', 'push_logs', ['service_name', 'created_at'], unique=False)
    op.create_index('idx_push_status_created', 'push_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_push_task_id', 'push_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_push_task_id', table_name='push_logs')
    op.drop_index('idx_push_status_created', table_name='push_logs')
    op.drop_index('idx_push_service_created', table_name='push_logs')
    op.drop_index('idx_push_receiver_created', table_name='push_logs')
    op.drop_table('push_logs')
    # ### end Alembic commands ###