"""ref2

Revision ID: 33fc5a36fe29
Revises: 3756faf95a8a
Create Date: 2026-02-10 20:14:06.137905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33fc5a36fe29'
down_revision = '3756faf95a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_id', name='unique_contact')
    )
    op.create_index(op.f('ix_trusted_contacts_contact_id'), 'trusted_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_id'), 'trusted_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_owner_id'), 'trusted_contacts', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_messageackevents_id'), table_name='messageackevents')
    op.drop_table('messageackevents')
    op.drop_index(op.f('ix_subscription_types_id'), table_name='subscription_types')
    op.drop_table('subscription_types')
    op.drop_index(op.f('ix_message_favorites_id'), table_name='message_favorites')
    op.drop_table('message_favorites')
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_table('friendships')
    op.add_column('messages', sa.Column('msg_type', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('sender_bipupu_id', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('receiver_bipupu_id', sa.String(length=50), nullable=False))
    op.drop_index(op.f('idx_created_range'), table_name='messages')
    op.drop_index(op.f('idx_deleted_at'), table_name='messages')
    op.drop_index(op.f('idx_receiver_created_at'), table_name='messages')
    op.drop_index(op.f('idx_receiver_is_read'), table_name='messages')
    op.drop_index(op.f('idx_receiver_is_read_created'), table_name='messages')
    op.drop_index(op.f('idx_receiver_sender_created'), table_name='messages')
    op.drop_index(op.f('idx_sender_created_at'), table_name='messages')
    op.drop_index(op.f('idx_type_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_delivered_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_read_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_title'), table_name='messages')
    op.create_index('idx_msg_type', 'messages', ['msg_type', 'created_at'], unique=False)
    op.create_index('idx_receiver_created', 'messages', ['receiver_bipupu_id', 'created_at'], unique=False)
    op.create_index('idx_sender_created', 'messages', ['sender_bipupu_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_msg_type'), 'messages', ['msg_type'], unique=False)
    op.create_index(op.f('ix_messages_receiver_bipupu_id'), 'messages', ['receiver_bipupu_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_bipupu_id'), 'messages', ['sender_bipupu_id'], unique=False)
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_deleted_by_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'title')
    op.drop_column('messages', 'deleted_reason')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'priority')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'deleted_by')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'delivered_at')
    op.add_column('users', sa.Column('bipupu_id', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('cosmic_profile', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_bipupu_id'), 'users', ['bipupu_id'], unique=True)
    op.create_unique_constraint('unique_bipupu_id', 'users', ['bipupu_id'])
    op.create_unique_constraint('unique_username', 'users', ['username'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('unique_username', 'users', type_='unique')
    op.drop_constraint('unique_bipupu_id', 'users', type_='unique')
    op.drop_index(op.f('ix_users_bipupu_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'cosmic_profile')
    op.drop_column('users', 'bipupu_id')
    op.add_column('messages', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('status', postgresql.ENUM('UNREAD', 'READ', 'ARCHIVED', name='messagestatus'), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('message_type', postgresql.ENUM('SYSTEM', 'USER', 'ALERT', 'NOTIFICATION', name='messagetype'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('deleted_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_deleted_by_fkey'), 'messages', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_index(op.f('ix_messages_sender_bipupu_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_bipupu_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_msg_type'), table_name='messages')
    op.drop_index('idx_sender_created', table_name='messages')
    op.drop_index('idx_receiver_created', table_name='messages')
    op.drop_index('idx_msg_type', table_name='messages')
    op.create_index(op.f('ix_messages_title'), 'messages', ['title'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_read_at'), 'messages', ['read_at'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messages_delivered_at'), 'messages', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_type_status'), 'messages', ['message_type', 'status', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_sender_created_at'), 'messages', ['sender_id', 'created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_receiver_sender_created'), 'messages', ['receiver_id', 'sender_id', 'created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_receiver_is_read_created'), 'messages', ['receiver_id', 'is_read', 'created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_receiver_is_read'), 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_receiver_created_at'), 'messages', ['receiver_id', 'created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_created_range'), 'messages', ['created_at', 'is_deleted'], unique=False)
    op.drop_column('messages', 'receiver_bipupu_id')
    op.drop_column('messages', 'sender_bipupu_id')
    op.drop_column('messages', 'msg_type')
    op.create_table('friendships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('friendships_friend_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('friendships_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('friendships_pkey'))
    )
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.create_table('message_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_favorites_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_favorites_pkey')),
    sa.UniqueConstraint('user_id', 'message_id', name=op.f('unique_user_message_favorite'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_message_favorites_id'), 'message_favorites', ['id'], unique=False)
    op.create_table('subscription_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subscription_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('default_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_types_pkey'),
    sa.UniqueConstraint('name', name='subscription_types_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_subscription_types_id'), 'subscription_types', ['id'], unique=False)
    op.create_table('messageackevents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('messageackevents_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messageackevents_pkey'))
    )
    op.create_index(op.f('ix_messageackevents_id'), 'messageackevents', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notification_time_start', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('notification_time_end', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_types.id'], name=op.f('user_subscriptions_subscription_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.drop_index(op.f('ix_trusted_contacts_owner_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_contact_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    # ### end Alembic commands ###