"""add userid

Revision ID: 888a5f5bad86
Revises: c0ab1c07bfb2
Create Date: 2026-02-26 23:28:54.312576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a5f5bad86'
down_revision = 'c0ab1c07bfb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_contacts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('trusted_contacts', sa.Column('contact_bipupu_id', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_trusted_contacts_contact_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_owner_id'), table_name='trusted_contacts')
    op.drop_constraint(op.f('unique_contact'), 'trusted_contacts', type_='unique')
    op.create_unique_constraint('unique_contact', 'trusted_contacts', ['user_id', 'contact_bipupu_id'])
    op.create_index(op.f('ix_trusted_contacts_contact_bipupu_id'), 'trusted_contacts', ['contact_bipupu_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_user_id'), 'trusted_contacts', ['user_id'], unique=False)
    op.drop_constraint(op.f('trusted_contacts_owner_id_fkey'), 'trusted_contacts', type_='foreignkey')
    op.drop_constraint(op.f('trusted_contacts_contact_id_fkey'), 'trusted_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'trusted_contacts', 'users', ['user_id'], ['id'])
    op.drop_column('trusted_contacts', 'contact_id')
    op.drop_column('trusted_contacts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_contacts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trusted_contacts', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trusted_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('trusted_contacts_contact_id_fkey'), 'trusted_contacts', 'users', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('trusted_contacts_owner_id_fkey'), 'trusted_contacts', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_trusted_contacts_user_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_contact_bipupu_id'), table_name='trusted_contacts')
    op.drop_constraint('unique_contact', 'trusted_contacts', type_='unique')
    op.create_unique_constraint(op.f('unique_contact'), 'trusted_contacts', ['owner_id', 'contact_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trusted_contacts_owner_id'), 'trusted_contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_contact_id'), 'trusted_contacts', ['contact_id'], unique=False)
    op.drop_column('trusted_contacts', 'contact_bipupu_id')
    op.drop_column('trusted_contacts', 'user_id')
    # ### end Alembic commands ###