"""remove user-push time

Revision ID: 94e7401ef089
Revises: f565ed255e6a
Create Date: 2026-02-21 14:51:02.597176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e7401ef089'
down_revision = 'f565ed255e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fortune_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fortune_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###