"""add_waveform_field_to_messages

Revision ID: 9e68d162be50
Revises: 94e7401ef089
Create Date: 2026-02-23 16:01:00.829505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e68d162be50'
down_revision = '94e7401ef089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('waveform', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'waveform')
    # ### end Alembic commands ###