"""Initial migration

Revision ID: a8b97ec18994
Revises: 
Create Date: 2026-02-07 18:50:16.885791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8b97ec18994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_admin_logs_admin_id")
    op.execute("DROP INDEX IF EXISTS ix_admin_logs_id")
    op.execute("DROP TABLE IF EXISTS admin_logs")
    op.add_column('users', sa.Column('avatar_data', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_mimetype', sa.String(length=50), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('users', 'avatar_mimetype')
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'avatar_data')
    op.create_table('admin_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('admin_logs_admin_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_logs_pkey'))
    )
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    # ### end Alembic commands ###