"""remove avatar vision

Revision ID: c0ab1c07bfb2
Revises: c67ee43869cf
Create Date: 2026-02-26 20:42:06.665750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ab1c07bfb2'
down_revision = 'c67ee43869cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_accounts', 'avatar_version')
    op.drop_column('users', 'avatar_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('service_accounts', sa.Column('avatar_version', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###