"""remove CosmicProfile

Revision ID: c67ee43869cf
Revises: faa0738bacb2
Create Date: 2026-02-26 02:59:51.327077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c67ee43869cf'
down_revision = 'faa0738bacb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('zodiac', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bazi', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('mbti', sa.String(length=4), nullable=True))
    op.add_column('users', sa.Column('birth_time', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('birthplace', sa.String(length=100), nullable=True))
    op.drop_column('users', 'cosmic_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cosmic_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'birthplace')
    op.drop_column('users', 'birth_time')
    op.drop_column('users', 'mbti')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'bazi')
    op.drop_column('users', 'age')
    op.drop_column('users', 'zodiac')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###