"""alter avatar

Revision ID: f565ed255e6a
Revises: 0c5320d8f6c4
Create Date: 2026-02-21 14:01:28.615811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f565ed255e6a'
down_revision = '0c5320d8f6c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_accounts', sa.Column('avatar_version', sa.Integer(), nullable=True))
    op.add_column('service_accounts', sa.Column('default_push_time', sa.Time(), nullable=True))
    op.drop_column('service_accounts', 'avatar_mimetype')
    op.drop_column('service_accounts', 'avatar_filename')
    op.add_column('subscriptions', sa.Column('push_time', sa.Time(), nullable=True))
    op.add_column('subscriptions', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('avatar_version', sa.Integer(), nullable=True))
    op.drop_column('users', 'avatar_mimetype')
    op.drop_column('users', 'avatar_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_mimetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_version')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'is_enabled')
    op.drop_column('subscriptions', 'push_time')
    op.add_column('service_accounts', sa.Column('avatar_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('service_accounts', sa.Column('avatar_mimetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('service_accounts', 'default_push_time')
    op.drop_column('service_accounts', 'avatar_version')
    # ### end Alembic commands ###