"""add_posters_table

Revision ID: faa0738bacb2
Revises: 9e68d162be50
Create Date: 2026-02-23 21:25:20.821119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa0738bacb2'
down_revision = '9e68d162be50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='海报标题'),
    sa.Column('image_data', sa.LargeBinary(), nullable=False, comment='海报图像数据（base64编码）'),
    sa.Column('link_url', sa.String(length=500), nullable=True, comment='点击跳转链接'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序，数字越小越靠前'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posters_display_order'), 'posters', ['display_order'], unique=False)
    op.create_index(op.f('ix_posters_id'), 'posters', ['id'], unique=False)
    op.create_index(op.f('ix_posters_is_active'), 'posters', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posters_is_active'), table_name='posters')
    op.drop_index(op.f('ix_posters_id'), table_name='posters')
    op.drop_index(op.f('ix_posters_display_order'), table_name='posters')
    op.drop_table('posters')
    # ### end Alembic commands ###